openapi: 3.0.0
info:
  title: Request Documentation API
  version: 1.0.0
  description: API for handling document requests.
servers:
  - url: "http://localhost:3000"
    description: Local server

components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: x-api-key

paths:
  /document-requests/documents:
    get:
      summary: Retrieve all documents
      description: Fetches a list of documents by language.
      security:
        - ApiKeyAuth: [] # Requires x-api-key header
      parameters:
        - in: query
          name: lang
          required: false
          schema:
            type: string
          description: The language of the documents (default is "en")
      responses:
        200:
          description: A list of documents
          content:
            application/json:
              schema:
                type: object
                properties:
                  language:
                    type: string
                  documents:
                    type: array
                    items:
                      type: object
                      properties:
                        doc_key:
                          type: string
                        value:
                          type: string

  /document-requests/newsfeed:
    get:
      summary: Retrieve newsfeed data
      description: Fetches a list of newsfeed entries showing documentation request status changes and operations.
      security:
        - ApiKeyAuth: [] # Requires x-api-key header
      parameters:
        - in: header
          name: customer
          required: false
          schema:
            type: string
          description: Optional customer ID to filter newsfeed entries for a specific customer
      responses:
        200:
          description: A list of newsfeed entries
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    customerId:
                      type: string
                      description: ID of the customer associated with the entry
                      example: "agxzfm1"
                    createdDate:
                      type: string
                      format: date-time
                      description: Date and time when the entry was created
                      example: "2025-09-10 04:11:57"
                    scope:
                      type: string
                      description: Scope of the operation (currently always "STATUS")
                      example: "STATUS"
                    operation:
                      type: string
                      enum: [INSERT, EDIT, DELETE]
                      description: Type of operation performed
                      example: "EDIT"
                    feedKey:
                      type: string
                      description: Unique ID associated with the entry
                      example: "agxz"
                    requestId:
                      type: string
                      description: ID of the documentation request
                      example: "1758589804023"
                    messageVariables:
                      type: object
                      description: Variables used in the message template
                      properties:
                        CUSTOMER_ID:
                          type: string
                          example: "1758240000000"
                        REQUEST_ID:
                          type: string
                          example: "1758589804023"
                        OLD_STATUS:
                          type: string
                          example: "ACTIVE"
                        NEW_STATUS:
                          type: string
                          example: "DONE"
                      additionalProperties: true
                    message:
                      type: string
                      description: Human-readable message describing the operation
                      example: "Customer <CUSTOMER_ID> changed request documentation status from <OLD_STATUS> to <NEW_STATUS>"
                    id:
                      type: integer
                      description: Unique identifier of the newsfeed entry
                    tenant_id:
                      type: string
                      description: Tenant ID (for backward compatibility)
                    old_status:
                      type: string
                      description: Previous status (for backward compatibility)
                      nullable: true
                    new_status:
                      type: string
                      description: New status (for backward compatibility)
                      nullable: true
                    changed_at:
                      type: string
                      format: date-time
                      description: Timestamp of the change (for backward compatibility)
        400:
          description: Bad request
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Bad request"
        500:
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Internal server error"

  /document-requests:
    post:
      summary: Create a document request
      description: Allows clients to request documentation from their customers.
      security:
        - ApiKeyAuth: [] # Requires x-api-key header
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                customer:
                  type: object
                  required: [id, name, email, languagePreference]
                  properties:
                    id:
                      type: string
                      description: Unique identifier for the customer
                    name:
                      type: string
                      description: Full name of the customer
                    email:
                      type: string
                      format: email
                      description: Email of the customer
                    languagePreference:
                      type: string
                      description: Preferred language of the customer (e.g., "en", "pt")
                    folder:
                      type: string
                      description: Folder Id where all documents should be stored
                documents:
                  type: array
                  items:
                    type: object
                    required: [key, quantity]
                    properties:
                      key:
                        type: string
                        description: Unique key representing the document type
                      quantity:
                        type: integer
                        description: Number of copies required

      responses:
        201:
          description: Document request created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  requestId:
                    type: string
                    description: Unique ID of the created request
                  message:
                    type: string
                    example: "Document request created successfully"
        400:
          description: Bad request, missing or invalid parameters
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Invalid request format"

  /document/upload:
    get:
      summary: Retrieve document upload details
      description: Fetches details for document upload using a token.
      parameters:
        - in: query
          name: token
          required: true
          schema:
            type: string
          description: Unique token identifying the document upload request
      responses:
        200:
          description: Details of the document upload request
          content:
            application/json:
              schema:
                type: object
                properties:
                  request_id:
                    type: string
                  box_key:
                    type: string
                  unique_link:
                    type: string
                  created_at:
                    type: string
                    format: date-time
                  expiry_date:
                    type: string
                    format: date-time
                  status:
                    type: string
                  language:
                    type: string
                  documents:
                    type: array
                    items:
                      type: object
                      properties:
                        key:
                          type: string
                        value:
                          type: string
                        quantity:
                          type: integer
